---
- hosts: all
  vars:
    virtualbox_version: "{{ lookup('url', 'https://download.virtualbox.org/virtualbox/LATEST.TXT') }}"
    kubernetes_version: "{{ lookup('url', 'https://storage.googleapis.com/kubernetes-release/release/stable.txt') }}"
    epson_generic_driver_url: "https://download3.ebz.epson.net/dsc/f/03/00/10/49/18/41ef4e1bb2cb43759ae3173912fde3c37f9f4b98/epson-inkjet-printer-escpr_1.7.7-1lsb3.2_amd64.deb"
    epson_printer_utility_driver_url: "https://download3.ebz.epson.net/dsc/f/03/00/11/87/09/33a8d4bfc7db0608b4f46cc95ac3fbbb3cbc01ab/epson-printer-utility_1.1.1-1lsb3.2_amd64.deb"
    epson_scanner_driver_url: "https://download2.ebz.epson.net/imagescanv3/ubuntu/lts1/deb/x64/imagescan-bundle-ubuntu-20.04-3.63.0.x64.deb.tar.gz"
  roles:
    - common
    - printer
    - work
